# ----------------------------------------------------------------
accounts:
  - name: "CN"           # 账号名称，方便识别
    storefront: "cn"     # 账号所属区域 (必须小写, 如 cn, us, jp, hk)
    media-user-token: "your-media-user-token"
    # authorization-token: "your-cn-auth-token" # 可选，如果留空或为 "your-authorization-token"，程序会自动获取
    decrypt-m3u8-port: "192.168.64.16:7778" # 此账号对应的解密服务端口
    get-m3u8-port: "192.168.64.16:7779"     # 此账号对应的M3U8获取服务端口
# ----------------------------------------------------------------
# 播放记录同步 (Scrobbling)
# ----------------------------------------------------------------
scrobble:
  enable: true
  
  # ListenBrainz 配置 (最简单，只需填入 User Token)
  # 获取地址: https://listenbrainz.org/profile/
  listenbrainz:
    enable: true
    token: "你的token"
# ----------------------------------------------------------------
  # Last.fm 配置
  # 申请 API: https://www.last.fm/api/account/create
  lastfm:
    enable: true
    api_key: "你的key"
    api_secret: "你的key"
# ----------------------------------------------------------------   
    # 如果你没有 Session Key，程序第一次运行时会自动用下面的账号密码去换取并打印出来，不建议
    username: ""
    password: ""
    # 建议执行 fm.py 获取lastfm 的 session_key 后填入
    session_key: "你的key"
# ----------------------------------------------------------------    
# 是否开启全区域解密
# true: 使用所有配置的账号（CN, JP, US ...）解密
# false: 仅使用与链接区域匹配的账号解密
global-decryption: false
# ----------------------------------------------------------------
# 下载保存路径设置
alac-save-folder: "./music"
atmos-save-folder: "./music"
# ----------------------------------------------------------------
# 是否开启 CDN true 开启，false 关闭
# 开启后, 将把音频 aod.itunes.apple.com 视频 mvod.itunes.apple.com 的流量重定向到下面指定的CDN
enable-cdn-override: false
# CDN IP
# 台湾 17.253.117.201，17.253.117.202，17.253.117.203
# 香港 17.253.85.201，17.253.85.202，17.253.85.203，17.253.85.204，17.253.85.205，17.253.85.206，17.253.87.195，17.253.87.196，17.253.87.201，17.253.87.203
# 日本 17.253.69.200，17.253.69.202，17.253.75.201，17.253.75.202
# 格式1：ip 为音视频通用，格式2：ip,ip 前面的为音频 CDN 逗号后面为视频 CDN，如：cdn-ip: "17.253.117.201,17.253.85.201"
cdn-ip: "17.253.117.201"
# ----------------------------------------------------------------
# Qobuz 账号配置 (用于获取PDF和专辑介绍)，尽量使用 fr 法区
qobuz-username: "" # 你的 Qobuz 邮箱
qobuz-password: "" # 你的 Qobuz 密码
# ----------------------------------------------------------------  
# 语言代码, 例如 "zh-CN", "en-GB"，"en-US" 留空则自动检测
# 各区域支持的语言列表: https://gist.github.com/itouakirai/c8ba9df9dc65bd300094103b058731d0
# 尽量使用英文"en-GB" "en-US" 歌手 - 专辑名 去匹配 Qobuz
language: "zh-CN" 
# ---------------------------------------------------------------- 
# 歌词设置
# 自动识别链接的区域并使用此区域的账号获取歌词
# 当发起任务的链接区域不在账号列表时,可选账号列表下的区域为默认下载歌词区域
default-lyric-storefront: "cn"
# ---------------------------------------------------------------- 
lrc-type: "syllable-lyrics"    # 可选: "lyrics" (普通歌词) 或 "syllable-lyrics" (逐字歌词与翻译)
lrc-format: "lrc"     # 可选: "lrc" 或 "ttml"
embed-lrc: false       # 是否将歌词嵌入音频文件
save-lrc-file: false  # 是否将歌词另存为 .lrc 文件
# ---------------------------------------------------------------- 
# 是否开启歌词翻译
enable-translation: false
# 官方目标语言: zh-Hans-CN (简体), zh-Hant-TW (繁体), ja (日文), ko (韩文)
translation-language: "zh-Hans-CN"
# ----------------------------------------------------------------
# 第三方目标语言: zh-Hans (简体), zh-Hant (繁体), en (英文)
translation-language: "zh-Hans" 
# --- 第三方翻译 api 选择 ---
# "libretranslate" "tencent" "deepl" "microsoft" "google"
translator-provider: "tencent"

#1. 自建libretranslate，无字符数量限制
libre_translate:
  url: "https://translator.kimu.edu.kg"  # 填入你刚才搭建的 API 地址
  api_key: ""                   # 如果你刚才没设置key，留空；设置了就填这里
  
# --- 第三方 api 详细配置 (仅需填写你选择的那一家) ---
# 2. 腾讯云 (推荐国内使用, 500万字符/月免费)
# SecretId:AKIDcQ3ScYHm25uVr13ykWHqZ8WheYO2fDbl
# SecretKey:0nMjurb8QWO1QbXTOF96vc6MOBMNBl62
tencent:
  secret-id: "AKIDcQ3ScYHm25uVr13ykWHqZ8WheYO2fDbl"    # 填写 SecretId
  secret-key: "0nMjurb8QWO1QbXTOF96vc6MOBMNBl62"       # 填写 SecretKey
  region: "ap-shanghai"                                # api 服务器地区

# 3. DeepL (50万字符/月免费)
deepl:
  auth-key: ""     # 填写 AuthKey (免费版通常以:fx结尾)
  is-pro: false    # 是否为 Pro 版

# 4. 微软 Azure (200万字符/月免费)
microsoft:
  key: ""
  region: "eastasia"

# 5. 谷歌 (需魔法网络)
google:
  api-key: ""
# ----------------------------------------------------------------  
#################################
#经常下载失败请按自身网络环境调整参数 #
# m3u8切片数量。                  #
chunk_downloadthreads: 10       #
# 网络块大小                      #
NetworkReadBufferKB: 4096 # kb  #
# I/O缓冲，过大将导致内存占用过高    #
BufferSizeKB: 4 # kb            #
# 下载线程数，最低为 1             #
aac_downloadthreads: 8          #
lossless_downloadthreads: 8     #
hires_downloadthreads: 8        #
#################################
# ---------------------------------------------------------------- 
# go run main.go 直接回车执行txt模式
# 从txt文件下载时，同时进行1个任务，过多任务有可能导致下载不稳定
txtDownloadThreads: 1
# ----------------------------------------------------------------  
#是否开启下载完成ffmpeg检测，并重新编码
ffmpeg-fix: false
#ffmpeg检测参数，可自行调整
ffmpeg-check-args: "-v error -f null -"
#ffmpeg重编码参数，可自行调整
ffmpeg-encode-args: "-map 0:a -map 0:v -c:a alac -c:v copy -f mp4"
# ---------------------------------------------------------------- 
# 封面与插图设置
embed-cover: false
cover-size: "5000x5000"
cover-format: "jpg"             # 可选: "jpg", "png", "original"
save-artist-cover: false        #歌手头像
save-animated-artwork: false    # 需要 ffmpeg
emby-animated-artwork: false    # 需要 ffmpeg
# ---------------------------------------------------------------- 
# M3U8 获取模式
get-m3u8-from-device: false
get-m3u8-mode: "hires"    # 可选: "all" (获取所有) 或 "hires" (仅探测Hi-Res)
# ---------------------------------------------------------------- 
# 音频格式偏好
aac-type: "aac-lc"        # 可选: "aac-lc", "aac", "aac-binaural", "aac-downmix"
alac-max: 192000          # 可选: 192000, 96000, 48000, 44100
atmos-max: 2768           # 可选: 2768, 2448
download-videos: true     #是否下载视频 true开启，false关闭，需有效的 your-media-user-token 和 mp4decrypt 工具
mv-audio-type: "atmos"    # MV音轨偏好, 可选: "atmos", "ac3", "aac"
mv-max: 2160              # MV视频分辨率偏好
# ---------------------------------------------------------------- 
# 绝对路径字符限制,留空就自动检测系统：windows 255  linux/mac 4096 其他系统自行测试
max-path-length: 255
# 歌手，专辑，曲目名，各个字符最大限制
limit-max: 200
# ---------------------------------------------------------------- 
# 文件与文件夹命名格式
# 可用变量: {AlbumId}, {AlbumName}, {ArtistName}, {ReleaseDate}, {ReleaseYear}, {UPC}, {Copyright}, {Quality}, {Codec}, {Tag}, {RecordLabel}
album-folder-format: "{AlbumName}_AM({AlbumId})"
# 可用变量: {PlaylistId}, {PlaylistName}, {ArtistName}, {Quality}, {Codec}, {Tag}
playlist-folder-format: "{PlaylistName}"
# 可用变量: {SongId}, {SongNumer}, {SongName}, {DiscNumber}, {TrackNumber}, {Quality}, {Codec}, {Tag}
song-file-format: "{SongNumer}. {SongName}"
# 可用变量: {ArtistId}, {ArtistName}, {UrlArtistName}
artist-folder-format: "{UrlArtistName}" # 留空则不创建艺术家文件夹
# ---------------------------------------------------------------- 
# 特殊标签显示
explicit-choice: "[E]"
clean-choice: "[C]"
apple-master-choice: "[M]"
# ---------------------------------------------------------------- 
# 播放列表元数据策略
use-songinfo-for-playlist: false
dl-albumcover-for-playlist: false
